In [7]:
import pandas as pd
import numpy as np

df = pd.read_csv("../../datasets/WDN/simple_transformation_set_2/simple_transformation_set_2_0002.csv")
display(df)

def resample_counts(df, dt=0.05):
    time_col = "ElapsedTime[s]"
    x = df[time_col].to_numpy()
    new_time = np.arange(x.min(), x.max() + dt, dt)
    count_cols = df.columns.drop(time_col)

    df_interp = pd.DataFrame({time_col: new_time})
    for col in count_cols:
        df_interp[col] = np.interp(new_time, x, df[col].to_numpy())

    N = df_interp.loc[0, count_cols].sum()
    if N > 0:
        df_interp[count_cols] /= N

    return df_interp

df = resample_counts(df)
display(df)

       ElapsedTime[s]  A  B
0               0.000  0  0
1               0.003  0  0
2               0.006  0  0
3               0.009  0  0
4               0.012  0  0
...               ... .. ..
19996          59.988  0  0
19997          59.991  0  0
19998          59.994  0  0
19999          59.997  0  0
20000          60.000  0  0

[20001 rows x 3 columns]

      ElapsedTime[s]    A    B
0               0.00  0.0  0.0
1               0.05  0.0  0.0
2               0.10  0.0  0.0
3               0.15  0.0  0.0
4               0.20  0.0  0.0
...              ...  ...  ...
1196           59.80  0.0  0.0
1197           59.85  0.0  0.0
1198           59.90  0.0  0.0
1199           59.95  0.0  0.0
1200           60.00  0.0  0.0

[1201 rows x 3 columns]

In [1]:
import torch
from torch_geometric.data import Data, Batch

class TestData(Data):
    def __inc__(self, key, value, *args, **kwargs):
        if key in {
            'index_inc_test'
        }:
            return len(self.x)
        return super().__inc__(key, value, *args, **kwargs)

batch = Batch.from_data_list([
    TestData(x=torch.tensor([[1], [2], [3], [4]]),
             index_inc_test=torch.tensor([0, 2])),
    TestData(x=torch.tensor([[5], [6], [7]]),
             index_inc_test=torch.tensor([3]))
])

print(batch.index_inc_test)

/Users/yannikschroeder/env/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

tensor([0, 2, 7])